DraughtsBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: DraughtsBundle:Default:index }

# src/Draughts/DraughtsBundle/Resources/config/routing.yml
DraughtsBundle_homepage:
    pattern:  /
    defaults: { _controller: DraughtsBundle:Page:index }
    requirements:
        _method:  GET
        
DraughtsBundle_game:
    pattern: /game
    defaults: { _controller: DraughtsBundle:Game:game }
    requirements:
        _method: GET
        