# src/Draughts/DraughtsBundle/Resources/config/routing.yml

DraughtsBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: DraughtsBundle:Default:index }

DraughtsBundle_homepage:
    pattern:  /  
    defaults: { _controller: DraughtsBundle:Page:index }
    requirements:
        _method:  GET
        
DraughtsBundle_databaseCreate1:
    pattern:  /add1/{userName}/{positionId}
    defaults: { _controller: DraughtsBundle:Default:create1 }
    requirements:
        _method:  GET

DraughtsBundle_databaseCreate2:
    pattern:  /add2/{userName}/{positionId}
    defaults: { _controller: DraughtsBundle:Default:create2 }
    requirements:
        _method:  GET
        
DraughtsBundle_databaseShow:
    pattern:  /show/{id}
    defaults: { _controller: DraughtsBundle:Default:show }
    requirements:
        _method:  GET
        
DraughtsBundle_databaseUpdate:
    pattern:  /update/{id}/{positionId}
    defaults: { _controller: DraughtsBundle:Default:update }
    requirements:
        _method:  GET
        
DraughtsBundle_databaseDelete:
    pattern:  /delete/{id}
    defaults: { _controller: DraughtsBundle:Default:delete }
    requirements:
        _method:  GET
        
DraughtsBundle_game:
    pattern: /app_dev.php/game
    defaults: { _controller: DraughtsBundle:Game:game }
    requirements:
        _method: GET
        
DraughtsBundle_board:
    pattern: /app_dev.php/board
    defaults: { _controller: DraughtsBundle:Board:board }
    requirements:
        _method: GET        
        
DraughtsBundle_flush:
    pattern: /flush
    defaults: { _controller: DraughtsBundle:Game:newBoard }
    requirements:
        _method: GET
        
DraughtsBundle_form:
    pattern: /form
    defaults: { _controller: DraughtsBundle:Default:form }
    requirements:
        _method: GET|POST
