# src/Draughts/DraughtsBundle/Resources/config/routing.yml

DraughtsBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: DraughtsBundle:Default:index }

DraughtsBundle_homepage:
    pattern:  /  
    defaults: { _controller: DraughtsBundle:Page:index }
    requirements:
        _method:  GET
        
DraughtsBundle_databaseCreate:
    pattern:  /add
    defaults: { _controller: DraughtsBundle:Default:create }
    requirements:
        _method:  GET
        
DraughtsBundle_databaseShow:
    pattern:  /show/{id}
    defaults: { _controller: DraughtsBundle:Default:show }
    requirements:
        _method:  GET
        
DraughtsBundle_databaseUpdate:
    pattern:  /update/{id}
    defaults: { _controller: DraughtsBundle:Default:update }
    requirements:
        _method:  GET
        
DraughtsBundle_databaseDelete:
    pattern:  /delete/{id}
    defaults: { _controller: DraughtsBundle:Default:delete }
    requirements:
        _method:  GET
        
