parameters:
#    draughts.example.class: Draughts\DraughtsBundle\Example

services:
#    draughts.example:
#        class: %draughts.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
